name: Build Status
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: say hello
        run: echo "hello"
